stages:
  process_video:
    cmd: python app.py
    deps:
      - scripts/download_audio.py
      - scripts/transcribe.py
      - scripts/save_json.py
      - app.py
    outs:
      - downloads/raw_audio/
      - downloads/transcribed_text/
      - downloads/json_files/
