name: CI Pipeline

on: 
  push:
    branches:
      - main  

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          set -e  # Exit immediately if any command fails
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Setup DVC
        run: |
          set -e
          python -m pip install dvc
          dvc version  # Verify installation
          dvc doctor   # Check DVC health

      - name: Configure DVC Remote
        run: |
          set -e
          dvc remote list  # Debug: Check existing remotes
          if dvc remote list | grep -q 'myremote'; then
            dvc remote remove myremote
          fi
          dvc remote add -d myremote file:///home/runner/work/audio-extraction/audio-extraction/s3 --force
          dvc remote list  # Verify remote is added
          dvc status  # Check status
          dvc fetch   # Fetch missing files
          dvc pull    # Pull latest data

      - name: Run Pipeline
        run: |
          set -e
          dvc repro