name: CI Pipeline

on: 
  push:
    branches:
      - main  

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          set -e
          echo "Upgrading pip and installing dependencies..."
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Setup DVC with S3 Support
        run: |
          set -e
          echo "Installing DVC with S3 support..."
          python -m pip install "dvc[s3]"
          dvc version
          dvc doctor

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          set -e
          echo "Configuring AWS credentials..."
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region "$AWS_REGION"

          echo "Verifying AWS connection..."
          aws s3 ls s3://audiocollection/path/to/data || { echo "AWS authentication failed!"; exit 1; }

      - name: Initialize DVC
        run: |
          set -e
          echo "Initializing DVC..."
          dvc init --quiet || true  # Prevent error if already initialized

      - name: Configure DVC Remote (AWS S3)
        run: |
          set -e
          echo "Configuring DVC remote..."
          if dvc remote list | grep -q 'myremote'; then
            echo "Removing existing 'myremote'..."
            dvc remote remove myremote
          fi

          dvc remote add -d myremote s3://audiocollection/path/to/data --force
          dvc remote modify myremote region "$AWS_REGION"
          dvc remote modify myremote access_key_id "$AWS_ACCESS_KEY_ID"
          dvc remote modify myremote secret_access_key "$AWS_SECRET_ACCESS_KEY"

          echo "DVC remote successfully configured."
          dvc remote list
          dvc remote default myremote

      - name: Fetch & Pull DVC Data
        run: |
          set -e
          echo "Fetching and pulling latest DVC data..."
          dvc pull || { echo "DVC pull failed! Check if data exists."; exit 1; }

      - name: Run DVC Pipeline
        run: |
          set -e
          echo "Running DVC pipeline..."
          dvc repro
