name: CI Pipeline

on: 
  push:
    branches:
      - main  

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          set -e  # Exit immediately if any command fails
          echo "Upgrading pip and installing dependencies..."
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Setup DVC with S3 Support
        run: |
          set -e
          echo "Installing DVC with S3 support..."
          python -m pip install "dvc[s3]"
          dvc version  # Verify installation
          dvc doctor   # Check DVC health

      - name: Configure AWS Credentials
        run: |
          set -e
          echo "Configuring AWS credentials..."
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          
          echo "Verifying AWS connection..."
          aws s3 ls || { echo "AWS authentication failed!"; exit 1; }

      - name: Configure DVC Remote (AWS S3)
        run: |
          set -e
          echo "Checking existing DVC remotes..."
          dvc remote list || true  # Prevent failure if no remote exists

          # Check if 'myremote' exists
          if dvc remote list | grep -q 'myremote'; then
            echo "Removing existing 'myremote'..."
            dvc remote remove myremote
          fi

          echo "Adding new DVC remote..."
          dvc remote add -d myremote s3://audiocollection/path/to/data --force
          dvc remote modify myremote region us-east-1

          echo "DVC remote successfully configured."
          dvc remote list  # Verify remote setup

      - name: Fetch & Pull DVC Data
        run: |
          set -e
          echo "Checking DVC status..."
          dvc status || true  # Allow non-zero exit codes

          echo "Fetching and pulling latest data..."
          dvc fetch
          dvc pull

      - name: Run DVC Pipeline
        run: |
          set -e
          echo "Running DVC pipeline..."
          dvc repro
