name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set region "$AWS_REGION"

      - name: Verify AWS Authentication
        run: |
          aws sts get-caller-identity
          aws s3 ls s3://audiocollection/path/to/data || echo "S3 path might not exist."

      - name: Verify DVC Initialization
        run: |
          if [ ! -d ".dvc" ]; then
            echo "DVC not initialized. Initializing..."
            dvc init --quiet
          fi

      - name: Configure DVC Remote (AWS S3)
        run: |
          dvc remote add -d myremote s3://audiocollection/path/to/data --force
          dvc remote modify myremote region "${{ secrets.AWS_REGION }}"

      - name: Fetch & Pull DVC Data
        run: |
          if ls *.dvc 1> /dev/null 2>&1; then
            dvc pull || echo "DVC pull failed!"
          fi

      - name: Run DVC Pipeline
        run: dvc repro

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Authenticate Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway auth --token "$RAILWAY_TOKEN"
          railway whoami

      - name: Link and Deploy to Railway
        env:
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          railway link "$RAILWAY_PROJECT_ID"
          railway up
