name: CI Pipeline

on: 
  push:
    branches:
      - main  

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Setup DVC
        run: |
          pip install dvc  # Ensure DVC is installed
          dvc version  # Verify installation

      - name: Configure DVC Remote (Local Storage)
        run: |
          dvc remote remove s3 || true  # Remove existing remote if it exists (avoids error)
          dvc remote add -d s3 file:///home/runner/work/audio-extraction/audio-extraction/s3 --force
          dvc pull


      - name: Run Pipeline
        run: |
          dvc repro
