name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-audio-app:latest -f Dockerfile .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-audio-app:latest

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Authenticate with Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Link Railway Project
        run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Deploy to Railway
        run: railway up --service backend
