name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[s3]  # Install DVC with S3 support

      - name: Configure AWS for DVC
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          dvc remote modify myremote access_key_id "$AWS_ACCESS_KEY_ID"
          dvc remote modify myremote secret_access_key "$AWS_SECRET_ACCESS_KEY"
          dvc remote modify myremote region "$AWS_REGION"

      - name: Pull DVC Data (Model/Assets)
        run: |
          dvc pull || echo "No DVC data to pull."
      
      - name: Run Tests
        run: |
          dvc repro --pull --force --run-cache 
          
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Authenticate & Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          railway auth --token "$RAILWAY_TOKEN"
          railway link "$RAILWAY_PROJECT_ID"
          railway up --service backend
